### PR TITLE
Allow fetching by texture IDs

### LINKED ISSUE #25: Support for texture IDs
The ability to request a player head directly via texture id, `http://textures.minecraft.net/texture/<texture id>`, for example `http://textures.minecraft.net/texture/f4f5b52d9ad21cfa175c4bde8314be44ea0c448afe531939e1a22ed11a665c77`

### Why?

Avoiding the cache that's bound to the UUID, querying by texture id directly would result in having the right head, right after the player's skin is changed.

Or if the (*online*) UUID isn't known but the texture id is, that would avoid 2 requests (username->uuid & uuid->profile)

### PR DESCRIPTION
**Pull request by TibiNonEst**
Closes #25. This allows you to fetch any resource by its texture ID.

There are two main things to consider with this pr:

1. Using solely texture IDs, there is no way of knowing whether the skin is of the "slim" model variety or not. This is for the most part a non-issue, however, it causes problems with body rendering. It also means that any request by texture ID will return an`X-Crafthead-Skin-Model` header of `default`.
2. There is also no way of knowing whether the texture is for a skin or cape. Currently, the pr just yolo's it, and requesting a cape just renders the texture as a cape even if it is a skin, and vice versa. This can cause very cursed images, but I guess if someone's requesting texture IDs directly they've probably done the due diligence of knowing what they need.

### CODE REVIEW

**Comment by TibiNonEst** [comment]
Given people have to know what texture ID to fetch anyway, it's not unreasonable to expect them to know whether or not a skin needs to have a slim model. If we can assume that, it might be helpful to provide a way to request a slim model, perhaps with a query parameter such as `?slim` or `?model=slim`.

**Comment by TibiNonEst** [comment]
Ignore the force-pushing and weird order of commits, I messed something up trying to fix the model query compat but I fixed it.

**Comment by FN-FAL113** [comment]
This would be handy and opens up support for custom skins that are cached in the texture.minecraft.net/

**Comment by FN-FAL113** [comment]
bump

**Comment by Hazmi35** [comment]
Hello. What are the status on this PR?

**Comment by Cherry** [comment]
Apologies for the delay in getting back to this. We've done a lot of maintenance on this repo since this PR was opened. Is this something folks are still wanting/needing?

**Comment by FN-FAL113** [comment]
> Apologies for the delay in getting back to this. We've done a lot of maintenance on this repo since this PR was opened. Is this something folks are still wanting/needing?

yes please, It would be a great addition.

**Comment by Cherry** [comment]
I've updated this for the most recent repo changes @TibiNonEst and would love your thoughts.

**Comment by Cherry** [comment]
Going to merge this, thanks for the PR! We may need to add some proxying of the texture requests if they're frequent/blocked, but this is great for now.

**Review by Cherry — APPROVED** [review]

**Pull request merged**
