### PR TITLE
chore: rust maintenance

### PR DESCRIPTION
**Pull request by Cherry**
- Removes `wee-alloc` due to lack of maintenance
- Adds rustfmt config and format all files

### CODE REVIEW

**Comment by astei** [comment]
I only had `wee_alloc` because of the Workers cold start problem, should've taken it out long ago

**Comment by astei** [comment]
There is [`lol_alloc`](https://github.com/craig-macomber/lol_alloc), should we want to still use a small allocator.

**Comment by astei** [comment]
Probably doesn't matter too much anyway.

**Comment by Cherry** [comment]
Good to know! Thanks for the insight. Hopefully isn't really an issue we have to worry about anymoroe.

**Pull request merged**
