### PR TITLE
Improve cube rendering

### PR DESCRIPTION
**Pull request by TibiNonEst**
The goal of this pr is to add general improvements to the cube head rendering feature.

- [x] Add head overlay option to render
- [x] Center render in png
- [x] Add depth shading
- [ ] Anti-alias hard edges

### CODE REVIEW

**Comment by TibiNonEst** [comment]
Currently, the branch renders the overlay textures directly on top of the cube, meaning it looks like one contiguous texture. While this is good for 2D renders, it may be more desirable to render them slightly offset from the head like how [Visage](https://visage.surgeplay.com) does.

**Comment by TibiNonEst** [comment]
The anti-aliasing I wanted to add doesn't seem currently possible with `imageproc`, I may return to it later, however.

**Comment by TibiNonEst** [comment]
Once this is done, #4 should be fairly straightforward which is nice, just gotta implement anti-aliasing first. I have an idea of how to do that but it would probably require no longer using `imageproc` and putting manual perspective warp code into `utils.rs`, but I'll see what works best without being overly jank,

**Comment by bribes** [comment]
> Once this is done, #4 should be fairly straightforward which is nice, just gotta implement anti-aliasing first. I have an idea of how to do that but it would probably require no longer using `imageproc` and putting manual perspective warp code into `utils.rs`, but I'll see what works best without being overly jank.

Nicee

**Comment by TibiNonEst** [comment]
Tfw I'm trying to comment and click the wrong button.

**Comment by TibiNonEst** [comment]
Anyway, I don't really know a good way of antialiasing cube renders while keeping the speed that `imageproc` provides. I think I might be able to skew it based on Minotar's `imgd` code but I would ideally like to continue using projections to do this so I really don't know.

**Comment by bribes** [comment]
> Anyway, I don't really know a good way of antialiasing cube renders while keeping the speed that `imageproc` provides. I think I might be able to skew it based on Minotar's `imgd` code but I would ideally like to continue using projections to do this so I really don't know.

Rip

**Comment by s-aditya-k** [comment]
this hasn't seem to be touched since april - maybe its time to split the antialiasing into a seperate PR and merge what's ready?

**Comment by Cherry** [comment]
Heey @TibiNonEst, thanks for this PR, and sorry for the review time! Is this something you're still interested in working on?

**Comment by yutotakano** [comment]
Is there anything on this PR that needs work other than the anti-aliasing? Seems good enough to merge to me.

**Comment by Cherry** [comment]
I've updated this for the most recent repo changes @TibiNonEst and would love your thoughts.

**Comment by Cherry** [comment]
I'm going to go ahead and merge this. If we want to followup with antialiasing, that can be done later. Thanks so much for the PR!

**Review by Cherry — APPROVED** [review]

**Pull request merged**
